platform :ios, ‘8.0’
use_frameworks!
target ‘SocialProject’ do

pod ‘Alamofire’
pod 'AlamofireImage'
pod 'SwiftyJSON'
pod 'IQKeyboardManagerSwift'
pod 'MJRefresh'
pod 'DNSPageView'
pod 'YLImagePickerController'
pod 'RongCloudIM/IMLib'
pod 'RongCloudIM/IMKit'
#pod 'RongCloudRTC/RongCallLib'
#pod 'RongCloudRTC/RongCallKit'

end
